/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    IconGithub: typeof import('./src/components/IconGithub.vue')['default']
    IconHome: typeof import('./src/components/IconHome.vue')['default']
    IconMenu: typeof import('./src/components/IconMenu.vue')['default']
    IconRSS: typeof import('./src/components/IconRSS.vue')['default']
    IconTwitter: typeof import('./src/components/IconTwitter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrapperDefault: typeof import('./src/components/WrapperDefault.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
