/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconGithub: typeof import('./src/components/IconGithub.vue')['default']
    IconMenu: typeof import('./src/components/IconMenu.vue')['default']
    IconTwitter: typeof import('./src/components/IconTwitter.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PhotoCard: typeof import('./src/components/PhotoCard.vue')['default']
    PhotosLayout: typeof import('./src/components/PhotosLayout.vue')['default']
    PhotoViewer: typeof import('./src/components/PhotoViewer.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WrapperDefault: typeof import('./src/components/WrapperDefault.vue')['default']
    WrapperPhotos: typeof import('./src/components/WrapperPhotos.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
